(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.SammeltjesStories = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  // Fixed recipients are part of the story. Other gifts use a small fitting pool.
  return [
    {id:"breinaalden", giverId:"schapenherdertje", targets:["oma-wierwortel"], fixed:true,
      item:"Breinaalden", icon:"needles", title:"Oma's geleende breinaalden",
      message:"Ik heb deze breinaalden van {target} geleend. Mijn sjaaltje is eindelijk af! Wil jij ze voor me terugbrengen?",
      thanks:"Mijn breinaalden! Dank je wel. Nu kan ik eindelijk verder met die sokken voor Opa.",
      story:"Het sjaaltje was af, de breinaalden kwamen thuis. Dankzij jou kan Oma weer verder breien."},
    {id:"bietensoep", giverId:"boer-bietje", targets:["oma-wierwortel"], fixed:true,
      item:"Verse bieten", icon:"beet", title:"Bietjes voor de soep",
      message:"Deze bieten zijn voor {target}. Ze maakt er zulke lekkere soep van. Wil jij ze brengen? Dan kan ik mijn aardappels nog even instoppen.",
      thanks:"Wat een prachtige bieten! Daar maak ik een grote pan soep van. Er is ook een kommetje voor jou.",
      story:"Van de akker naar Oma's soeppan: een klein mandje bieten maakte een hele keuken gezellig."},
    {id:"warme-sjaal", giverId:"dijkdraakje", targets:["dijkwacht"], fixed:true,
      item:"Warme sjaal", icon:"scarf", title:"Warm op de dijk",
      message:"Vannacht wordt het fris op de dijk. Ik heb een warme sjaal voor {target} klaargelegd. Wil je die brengen? Hij vergeet altijd goed voor zichzelf te zorgen.",
      thanks:"Voor mij? Ik dacht dat ik geen kou voelde, maar dit is toch wel heerlijk. Bedank Dijkdraakje maar!",
      story:"Op de dijk waaide het nog net zo hard. Maar met een sjaal van een vriend voelde de wind veel zachter."},
    {id:"windboek", giverId:"molenmaatje", targets:["opa-duinbaard"], fixed:true,
      item:"Boek over de wind", icon:"book", title:"Een boek vol wind",
      message:"{target} heeft me dit boek over de wind geleend. Sommige bladzijden wilden steeds wegwaaien! Wil je het terugbrengen en zeggen dat ik ervan genoten heb?",
      thanks:"Ah, mijn windboek! Er zit zelfs nog een briesje tussen de bladzijden. Fijn dat Molenmaatje ervan genoten heeft.",
      story:"Het windboek vond zijn weg terug naar Opa. De verhalen bleven nog een beetje tussen de molenwieken hangen."},
    {id:"bijzondere-schelp", giverId:"nettenvissertje", targets:["schelpenwachter"], fixed:true,
      item:"Bijzondere schelp", icon:"shell", title:"Een vondst in het net",
      message:"Er zat een heel bijzondere schelp in mijn net. {target} weet vast hoe hij heet. Wil jij hem brengen? Wel voorzichtig, hij is nog een beetje verlegen.",
      thanks:"Wat een mooie vondst! Deze krijgt een ereplekje. En Nettenvissertje krijgt straks het hele schelpenverhaal te horen.",
      story:"Een schelp uit een visnet werd een schat om samen te bewonderen. Jij bracht het kleine wonder langs."},
    {id:"schelpencadeau", giverId:"mosselmop", targets:["schelpenwachter","nettenvissertje","havenpluimpje","waddenwriemel"],
      item:"Cadeauschelpjes", icon:"shell", title:"De mooiste schelpjes",
      message:"Deze schelpen zijn een cadeautje voor {target}. Ik heb de mooiste uitgezocht. Nou ja... de allermooiste houd ik zelf. Wil jij de andere brengen?",
      thanks:"Heeft Mosselmop die voor mij uitgezocht? Ze zijn prachtig! Die ene die hij zelf houdt moet wel heel bijzonder zijn.",
      story:"Niet alle schelpen bleven in Mosselmops zak. Een handjevol werd een cadeautje vol vriendschap."},
    {id:"kruidenthee", giverId:"oma-wierwortel", targets:["opa-duinbaard","boer-bietje","dijkdraakje","kapel-kabbeltje","rietritter","schapenherdertje"],
      item:"Zakje kruidenthee", icon:"tea", title:"Een warm kopje aandacht",
      message:"Ik heb wat kruidenthee gemaakt voor {target}. Gewoon, omdat een warm kopje soms precies is wat je nodig hebt. Wil jij dit zakje brengen?",
      thanks:"Het ruikt nu al naar Oma's tuin. Wat lief dat ze aan me denkt. Ik zet meteen water op!",
      story:"In een klein zakje paste een hele tuin aan geuren, en een warm gebaar van Oma."},
    {id:"zacht-veertje", giverId:"wieringer-wolkje", targets:["havenpluimpje","molenmaatje","schelpenwachter","nettenvissertje","kwelder-sprietje"],
      item:"Zacht veertje", icon:"feather", title:"Een veertje uit de wolken",
      message:"Ik vond dit zachte veertje tussen mijn wolken. Het deed me aan {target} denken. Wil jij het geven? In mijn zak waait alles er steeds weer uit.",
      thanks:"Zo zacht! Ik bewaar het op een plekje zonder tocht. Wat fijn dat Wolkje aan me dacht.",
      story:"Het veertje waaide niet weg. Jij bracht het voorzichtig van de wolken naar een vriendje."},
    {id:"veldbloemen", giverId:"akkervonk", maxDistance:2000, targets:["boer-bietje","schapenherdertje","oma-wierwortel","kwelder-sprietje","rietritter"],
      item:"Boeket veldbloemen", icon:"flowers", title:"Bloemetjes zonder hommel",
      message:"Ik heb een boeketje veldbloemen voor {target} geplukt. Er zat eerst een hommel in, maar die is alweer naar huis. Wil je het brengen?",
      thanks:"Wat een kleuren! Daar word ik helemaal vrolijk van. En de hommel mag best eens op bezoek komen.",
      story:"Een klein boeket gaf de dag kleur. De hommel had zijn eigen plannen, maar de bloemen kwamen aan."},
    {id:"geluksarmband", giverId:"havenpluimpje", targets:["wieringer-wolkje","molenmaatje","schelpenwachter","nettenvissertje","mosselmop"],
      item:"Geluksarmbandje", icon:"bracelet", title:"Een knoopje vol geluk",
      message:"Ik heb van een stukje scheepstouw een geluksarmbandje gemaakt voor {target}. De knoop zit een beetje scheef, maar de gelukjes blijven er vast wel in.",
      thanks:"Juist dat scheve knoopje maakt het mooi. Ik doe het meteen om. Dank je wel voor het brengen!",
      story:"Een stukje scheepstouw kreeg een tweede leven. Het hield geen schip meer vast, maar een klein beetje geluk."},
    {id:"rietfluitje", giverId:"rietritter", targets:["schapenherdertje","boer-bietje","waddenwriemel","kwelder-sprietje","oma-wierwortel"],
      item:"Rieten fluitje", icon:"flute", title:"Het lied van de eend",
      message:"Ik heb een fluitje van riet gemaakt voor {target}. Het klinkt nog een beetje als een verkouden eend. Wil jij het brengen? Misschien krijgt die er een mooier liedje uit.",
      thanks:"Prrr... kwaak! Nee, bij mij klinkt het ook als een eend. Maar wel een hele vrolijke. Bedank Rietritter voor me!",
      story:"Het fluitje klonk niet helemaal zoals bedoeld. Gelukkig hoeft een cadeau niet perfect te zijn om plezier te geven."},
    {id:"verhalenbrief", giverId:"opa-duinbaard", maxDistance:3000, targets:["oma-wierwortel","molenmaatje","kapel-kabbeltje","mistmuis","stormster"],
      item:"Brief met een verhaal", icon:"letter", title:"Wat de wind nog wist",
      message:"Wil je dit briefje naar {target} brengen? Er staat een verhaal op dat ik bijna vergeten was. Gelukkig herinnerde de wind me eraan.",
      thanks:"Een verhaal van Opa! Daar ga ik rustig voor zitten. Zo fijn dat dit niet met de wind is verdwenen.",
      story:"Wat bijna vergeten was, kreeg een nieuw luisterend oor. Jij droeg Opa's verhaal verder."},
    {id:"gevonden-want", giverId:"dijkwacht", targets:["dijkdraakje","schapenherdertje","oma-wierwortel","waddenwriemel","rietritter"],
      item:"Gevonden want", icon:"mitten", title:"Geen koude hand meer",
      message:"Ik vond deze want tijdens mijn ronde. Volgens mij is hij van {target}. Wil jij hem terugbrengen? Een koude hand lijkt me zo ongezellig.",
      thanks:"Mijn want! Ik had al in al mijn zakken gekeken. Nu zijn ze weer samen. Wat fijn dat Dijkwacht zo goed oplet.",
      story:"Twee wanten horen bij elkaar. Dankzij een oplettende Dijkwacht en jouw ommetje zijn ze weer een paar."},
    {id:"bloemzaadjes", giverId:"kwelder-sprietje", targets:["schapenherdertje","mosselmop","nettenvissertje","waddenwriemel","akkervonk"],
      item:"Zakje bloemzaadjes", icon:"seeds", title:"Een zakje lente",
      message:"{target} wilde weten hoe ik zulke mooie bloemetjes krijg. Hier zijn wat zaadjes. Wil je ze brengen? Zeg maar dat zachtjes zingen misschien helpt.",
      thanks:"Dan zoek ik een mooi plekje in mijn tuintje. Het zingen durf ik wel te proberen, maar alleen als niemand luistert!",
      story:"In het zakje zat nog geen bloem. Wel een belofte van kleur, een beetje geduld en misschien een liedje."},
    {id:"glinstersteen", giverId:"goudglim", targets:["oma-wierwortel","boer-bietje","kapel-kabbeltje","mistmuis","stormster"],
      item:"Glinsterend steentje", icon:"stone", title:"Een glinstering voor jou",
      message:"Dit steentje glinstert bijna net zo mooi als ik. Het is voor {target}, omdat die laatst zo aardig was. Wil jij mijn cadeautje bezorgen?",
      thanks:"Goudglim heeft het onthouden! Het steentje is mooi, maar dat warme gebaar vind ik nog veel mooier.",
      story:"Een vriendelijk moment kreeg een glinsterend antwoord. Jij maakte het rondje vriendschap compleet."}
  ];
});
